# Generated by Django 3.1.3 on 2020-12-04 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True)),
                ('position', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('desc', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True)),
                ('degree', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True)),
                ('position', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='requirements.category')),
                ('rank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='requirements.rank')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=20)),
                ('desc', models.TextField(blank=True)),
                ('position', models.IntegerField()),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requirements.requirement')),
            ],
        ),
        migrations.CreateModel(
            name='Eligibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=20)),
                ('position', models.IntegerField()),
                ('desc', models.TextField(blank=True)),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requirements.rank')),
            ],
        ),
    ]
