# Generated by Django 3.0.8 on 2020-10-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='video_url',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
