# Generated by Django 3.0.8 on 2020-10-11 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0003_rank_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='assoc_rank',
        ),
        migrations.RemoveField(
            model_name='category',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='categories',
        ),
        migrations.AddField(
            model_name='category',
            name='rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='requirements.Rank'),
        ),
    ]
