# Generated by Django 3.0.8 on 2020-10-12 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0005_requirement_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='video_url',
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=20)),
                ('desc', models.TextField(blank=True)),
                ('position', models.IntegerField()),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requirements.Requirement')),
            ],
        ),
    ]
