# Generated by Django 3.0.8 on 2020-10-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hyung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('position', models.IntegerField()),
                ('video_url', models.CharField(max_length=200)),
                ('desc', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=20)),
                ('beltColor', models.CharField(max_length=20)),
                ('position', models.IntegerField()),
                ('eligibility', models.TextField(blank=True)),
                ('hyung', models.ManyToManyField(to='syllabi.Hyung')),
            ],
        ),
    ]
