# Generated by Django 3.0.8 on 2020-08-11 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rank',
            name='degree',
        ),
    ]
