# Generated by Django 3.0.8 on 2020-08-11 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabi', '0002_remove_rank_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='degree',
            field=models.CharField(default='9th Gup', max_length=20),
            preserve_default=False,
        ),
    ]
